### ISSUE TITLE
Update `requirements.txt` with specific versions

### ISSUE THREAD

**Issue by saattrupdan** [centre-for-humanities-computing/danish-foundation-models#16]
We should probably agree on specific versions of our dependencies to ensure that everything runs as intended.

@KennethEnevoldsen or @HLasse, do you know what version of CUDA we have available on our servers? Then we could just choose the newest versions that are compatible with those.

This issue is solely to decide on specific versions of the following packages, which are currently in our requirements file:
- `torch`
- `transformers`
- `datasets`
- @KennethEnevoldsen's `text-dedup` package
- `wasabi`

As soon as we agree on versions, I'll open a PR with the updated `requirements.txt`.

**Comment by KennethEnevoldsen** [comment]
This is what I currently have running on UCloud:

wasabi: 0.9.0
torch: 1.10.1+cu102
datasets: 1.17.0
transformers: 4.15.0

the text-dedup package is frozen.

**Comment by KennethEnevoldsen** [comment]
@saattrupdan I have added this is the latest update on main. If there is a problem please open a PR with suggested changes.
