### ISSUE TITLE
Dataset: Reddit-da

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#17]
- [ ] As mentioned in #7 the Reddit data isn't deduplicated.

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
No. I haven't worked on it. Maybe we should include it in the DAGW as a category. @HLasse can you do this?

**Comment by HLasse** [comment]
Sure 👍

**Comment by KennethEnevoldsen** [comment]
Adressed in #118
