### ISSUE TITLE
Data cleaning experiment plan

### ISSUE THREAD

**Issue by HLasse** [centre-for-humanities-computing/danish-foundation-models#177]
# Experiment 1

### Summary
We want to ensure that the effect of data cleaning is consistent across different model sizes. If this is true, we can conduct experiments with data cleaning on a smaller model to iterate faster to find optimal cleaning configurations.

To test this, we will train models of different sizes on datasets that have been cleaned to different extents. Models will be trained for some _n_ number of steps/tokens.

All models will be evaluated (perplexity) on the same held-out dataset consisting of different sections of DAGW which we are sure are "clean". 

Two ways of doing this:

1. Training randomly initialised models (all from same seed) of different sizes for n_steps/tokens.
**Pros**
All models have been trained on exactly the same data for the entire training
**Cons**
The weight initialization might play a fairly large role unless we train for a substantial number of tokens.

2. Continued training of pre-trained models of different sizes for n_steps/tokens.
**Pros**
Models are already close to convergence, which should make them more stable
**Cons**
Models have been trained on different datasets, so comparing across different sizes is not as straightforward. 

### Assumptions
Perplexity @ n_steps << max steps is a good proxy for perplexity @ convergence across all model sizes.

### Desired output
Hopefully, the effect of different levels/methods of cleaning is stable across model sizes. 

![image](https://github.com/centre-for-humanities-computing/danish-foundation-models/assets/23191638/ff686fa7-1b6a-4b4f-a563-427244614105)

**Comment by MartinBernstorff** [comment]
Looks great! Let's build upon this 👍
