### ISSUE TITLE
Accessing the Danish Colossal Corpus dataset

### ISSUE THREAD

**Issue by AIMads** [centre-for-humanities-computing/danish-foundation-models#194]
Hey I was wondering where it is possible to get access to the Danish Colossal Corpus dataset?

**Comment by HLasse** [comment]
Hi Mads. Unfortunately, most of the dataset is not publicly available. I see that you're affiliated with SDU -- as such there might be possibilities for collaborations within the project. Feel free to write a few sentences about your idea here, or reach out to me (Lasse Hansen) and/or Kenneth Enevoldsen on the DDSC slack (here's an invite link): https://join.slack.com/t/danskdatascie-o8m9638/shared_invite/zt-1jh2dwmj4-D_mjywfXERvVP75n9O0ykg
