### ISSUE TITLE
Gopher filter fails when encounter empty docs

### ISSUE THREAD

**Issue by TTTTao725** [centre-for-humanities-computing/danish-foundation-models#209]
https://github.com/allenai/dolma/blob/41ec1efb580457716fd7209de70974d66ba6f9fb/python/dolma/taggers/gopher.py#L103
When processing documents with no words

**Comment by KennethEnevoldsen** [comment]
We are awaiting a response here: https://github.com/allenai/dolma/pull/98

**Comment by peterbjorgensen** [comment]
Your pull request has been merged and this issue is therefore closed with this pull request https://github.com/centre-for-humanities-computing/danish-foundation-models/pull/234
