### ISSUE TITLE
Dataset: HopeTweet

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#3]
- [x] On UCloud 
- [x] HuggingFace format
- [x] quality filter
- [ ] deduplication

Potentially:
- [ ] troll filter

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
We still need the deduplication. Should be quick, will add it to my todo.

**Comment by KennethEnevoldsen** [comment]
Adressed in #119
