### ISSUE TITLE
Dataset: Netarkivet

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#34]
- [x] Move the dataset to UCloud
- [x] Dataset quality filtering of the dataset
- [ ] Dataset deduplication (ongoing)
~~- [ ] Dataset to HF format~~

**Comment by saattrupdan** [comment]
Is this done now?

**Comment by KennethEnevoldsen** [comment]
Deduplicating crashed due to the files system being offline. It crashed during writing the cache to had to restart it completely. I know write an new cache pr. year where e.g. the cache from 2008 contains the documents form all the year before (2006, 2007)

**Comment by KennethEnevoldsen** [comment]
This issue was completed a long time ago. Will close it.
