### ISSUE TITLE
Dataset Cleaning

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#39]
Creating a new issue related to dataset cleaning which is more detailed (see previous issue #7).

Dataset cleaning consist of multiple steps:

- [x] Language filtering
  - ~~FastText classifier (e.g. similar to [NBAilab](https://github.com/NBAiLab/notram/blob/master/corpus_generation_scripts/lang_detect_reddit.py))~~
  - [x] Used existing language tag by either Twitter (DaTwitter) or the Royal Danish Library (Netarkivet)
  - ~~Filtering .dk domains~~
- [x] Text extraction
  - ~~Extracting text from HTML and removing HTML markup (e.g. using [jusText](https://pypi.org/project/jusText/))~~
  - [x] Done by the Royal Danish Library

- [x] #40
  - [x] #41
- [ ] Quality Filtering
  - [ ] Missing DAGW, DaReddit (#17)
- [ ] Document deduplication
  - [ ] Exact deduplication
  - [ ] Near deduplication using 13-gram MinHash (see #11 )
- ~~Test set filtering~~ (only few Danish task for text generation)
- [ ] (Content filtering)
  - [ ] Pornography

  
We have debated filtering out hate speech, but a performance of <[80](https://scandeval.github.io)% was considered too low and might result in unforeseen artifacts like filtering out ethnic minorities, due to these having a higher chance of appearing in the context of hate speech.

## Application to the datasets
Naturally, not all of these steps are applied to all the datasets (☑️ indicating should be done ✅ indicating is done):

| Step | HopeTwitter | DAGW + lex.dk | DaNews | Reddit-da | Netarkivet | mC4 | 
| ---- | ------------ | ------- | ------- | ---------- | ---------- | --- |
| Language filtering | ✅ |       |           | ✅                |✅               |    |
| Text extraction |  |    |     |     |  ✅ |    |
| Quality filtering  | ✅  |  ☑️   |  ✅   |  ☑️   |  ✅ |    |
| Repitious text removal  | ✅ | ☑️   |  ✅   |  ☑️   |  ✅ |    |
| Document deduplication  | ☑️  | ☑️  |  ☑️   |  ☑️   |  ☑️ |   |
| Train/val/test split  | ☑️  | ☑️  |  ☑️   |  ☑️   |  ☑️ |   |

Language filtering: 
For HopeTwitter uses the Twitter language tags as well as must contain at least one Scandinavian stopword. Reddit-da is constructed using a Danish language filter over all of reddit, thus we have not reapplied a model.

**Comment by mollerhoj** [comment]
Exact deduplication: If we filter everything on sentence level as I propose, I don't believe exact deduplication is necessary? It will (easily) be picked up by the fuzzy dedup?

**Comment by KennethEnevoldsen** [comment]
I agree @mollerhoj, I simply expect it would be faster to check if it is an exact duplicate before as fuzzy dedup. If development time is the limiting factor it can def. be skipped.

**Comment by mollerhoj** [comment]
@KennethEnevoldsen I think fuzzy dedup either is or can be made extremely fast: IO should be the limiting factor. It could even be parallelized if we want to be fancy.

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
I have updated the main comment to reflect the progress.
