### ISSUE TITLE
Dataset: DaNews

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#4]
- [x] On UCloud
~~- [x]  HuggingFace format~~
- [ ] jsonl format
- [x] Quality filtered
- [ ] Deduplicated

**Comment by KennethEnevoldsen** [comment]
Hei @supplyandcommand this works looks good. Notices that we have a problem with the news dataset starting from 2005 and being ordered. This means that even if we implement a shuffle buffer we will not be able to properly shuffle the data. A solution to this would be to create an ndjson reader for each file and then read a line from each.

Could I also get you to do the same thing for the Twitter dataset.

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
It is not deduplicated, will put that on my todo.

**Comment by KennethEnevoldsen** [comment]
Addressed in #117
