### ISSUE TITLE
Quality filtering

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#40]
Heuristic filters: 

A document was *removed* if:
- [x] does not contain between 50 and 100,000 words
- [x] Mean word length is *not* in the range of 3 to 10 characters (estimate this for Danish)
- [x] symbol-to-word ratio greater than 0.1 for either the hash symbol or the ellipsis
- [x] any document with more than 90% of lines starting with a bullet point
- [x] or more than 30% ending with an ellipsis
- [x] if less than 80% of words in a document contain at least one alphabetic character
- [x] It did not contain at least one of the two "stop word":
  - 25 most popular Danish words (excluding "i"): `| er | jeg | det | du | ikke | at | en | og | har | vi | til | på | hvad | mig | med | de | for | den | så | der | dig | han | kan | af`

**Potentially:**
-  [x] Update the stopword list

Worked on in:
- #55 
- #49 
- #54 

Rae, J. W., Borgeaud, S., Cai, T., Millican, K., Hoffmann, J., Song, F., Aslanides, J., Henderson, S., Ring, R., Young, S., Rutherford, E., Hennigan, T., Menick, J., Cassirer, A., Powell, R., Driessche, G. van den, Hendricks, L. A., Rauh, M., Huang, P.-S., … Irving, G. (2021). Scaling Language Models: Methods, Analysis & Insights from Training Gopher. https://arxiv.org/abs/2112.11446v2

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
Indeed it is.
