### ISSUE TITLE
Training tokenizers

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#6]
Training tokenizers used for training

**Comment by saattrupdan** [comment]
Q: Would it make sense to train the tokeniser on a subset of the data, considering the massive size of the dataset? We could, e.g, pick a fixed portion of each dataset to balance out the frequency counts.

**Comment by KennethEnevoldsen** [comment]
Agree I was actually just thinking gigaword (+some Twitter as the dagw we have does not contain tweets), but I Think your approach is better. You can do this quite easy using hf datasets interleave and take methods. Though there might be some problems with length differences.

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Is this done now?

**Comment by KennethEnevoldsen** [comment]
It is not. We should train in on the final dataset. On this note I have added dataset split to the agenda tomorrow.

**Comment by KennethEnevoldsen** [comment]
@saattrupdan I have trained a few tokenizers by now, do we want to share them or only along with a model?

**Comment by KennethEnevoldsen** [comment]
Perfect I will then close this issue.
