### ISSUE TITLE
Cleaning scripts

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#7]
Ordered list of cleaning scripts:
- [ ] Use jusText to remove boilerplate HTML (also done in icelandic BERT)
- [ ] Filer non .dk domains patterns (inspired by the Icelandic BERT
- [ ] [Gopher](https://arxiv.org/pdf/2112.11446.pdf) style preprocessing [page 40, quality filtering]
- [ ] Language (using fasttext)
- [ ] Deduplication
- [ ] Fuzzy deduplication #11 or gopher [paper](https://arxiv.org/pdf/2112.11446.pdf) [page 40, repitious text removal]
- [ ] Kasper Junges classifier

**Potential additional steps:**
Norwegian group filtered using perplexity scores (similar to RoBERTa preprocessing) removing both very high and very low perplexity scores. (potentially ask Per from NBailab)

**Comment by KennethEnevoldsen** [comment]
@saattrupdan do you know if exact duplicates have been removed from the Reddit data?

**Comment by saattrupdan** [comment]
> @saattrupdan do you know if exact duplicates have been removed from the Reddit data?

@KennethEnevoldsen No duplicates have been removed, no. It's purely language detection. You can see the exact script they used here: https://github.com/NBAiLab/notram/blob/master/corpus_generation_scripts/lang_detect_reddit.py

**Comment by KennethEnevoldsen** [comment]
Ahhh, It should probably be quite easy to dedupe. I have added it as an issue. Might also relate to #11 .

**Comment by HLasse** [comment]
Make cleaning scripts for webdata (MC4/Netarkivet) inspired by the Icelandic BERT. 
Perhaps also use [jusText](https://github.com/miso-belica/jusText) to remove boilerplate html stuff (also done in icelandic BERT

**Comment by KennethEnevoldsen** [comment]
I have restructured this issue in #39 to more digestible tasks so will close this issue.
