### ISSUE TITLE
Can't continue deduplication with the deduper

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#82]
Currently, if the deduplication breaks you can load it up again from disk. However, you can't no longer continue to write to the existing mask saved on disk as it only appends to it.

A potential solution is to move the "output_dir" (potentially call it save dir) to the deduper.__init__ instead of the `.dedupe` method. You can still keep the output dir in the dedupe method for writing deduped files.

**Comment by saattrupdan** [comment]
Fixed in https://github.com/centre-for-humanities-computing/danish-foundation-models/pull/83.
